cache:
  directories:
    - sysconfcpus
before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      echo "Installing sysconfcpus";
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    else
      echo "Found sysconfcpus";
    fi

matrix:
  include:

    # Client
    - language: node_js
      node_js: v8
      before_install:
        - cd client
        - npm run reinstall
        - mv ./node_modules/.bin/elm-make ./node_modules/.bin/elm-make-origin
        - printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-origin \"\$@\"" > ./node_modules/.bin/elm-make
        - chmod +x ./node_modules/.bin/elm-make
      before_script:
        - which elm-make
        - npm config get prefix
        - elm-make -h
      script:
        - npm run build

    # Server
    - language: scala
      scala: 2.12.4
      jdk: oraclejdk8
      before_script:
        - cd server
      script:
        - sbt compile

