matrix:
  include:

    # Server
    - language: scala
      scala: 2.12.4
      jdk: oraclejdk8
      before_script:
        - cd server
      script:
        - sbt compile

    # Client
    - language: node_js
      node_js: v8
      before_install:
        - cd client
      install:
        - npm install
      before_script:
        - npm run reinstall
      script:
        - npm run build
