cache:
  directories:
    - sysconfcpus
before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      echo "\nInstalling sysconfcpus\n";
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    else
      echo "\nFound sysconfcpus\n";
    fi

matrix:
  include:

    # Server
    - language: scala
      scala: 2.12.4
      jdk: oraclejdk8
      before_script:
        - cd server
      script:
        - sbt compile

    # Client
    - language: node_js
      node_js: v8
      before_install:
        - cd client
        - npm run reinstall
        - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
        - printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
        - chmod +x $(npm config get prefix)/bin/elm-make
      before_script:
        - elm-make -h
      script:
        - npm run build
